# Generated by Django 4.1.1 on 2022-09-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('industry', models.CharField(max_length=50)),
                ('logo', models.ImageField(default='default.jpg', upload_to='logos')),
            ],
        ),
    ]
